spring:
  datasource:
    url: jdbc:postgresql://localhost:5678/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

server:
  port: 9090
  error:
    include-message: always