spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5678/driver_app
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 5656


driver-app:
  standart:
    landing: 60
    per-km: 12
  comfort:
    landing: 80
    per-km: 15
  business-class:
    landing: 100
    per-km: 20

